# Generated by Django 4.0.1 on 2022-01-06 12:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('videoPlayer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrlBookmarked',
            fields=[
                ('id_url', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=100)),
                ('add_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
